### ISSUE TITLE
Users cannot be removed from groups

### ISSUE THREAD

**Issue by minimuscle** [willmcpherson2/notcord#18]
Front end is set up so users can be removed from groups at the same time as they would be added, backend does not have this setup yet.

**Comment by Stokeometry** [comment]
created a remove_user_from_group route.
should allow a admin to delete anyone from a group or anyone to delete themselves
also cascades through channels & deletes users from there as well

Have to run some testing as it might have errors but i've pushed the route to backend-group branch

**Comment by minimuscle** [comment]
I'll setup the front end for it as well, with a confirmation on my end

**Comment by willmcpherson2** [comment]
Looks good @Stokeometry. Add a section to the [API](https://github.com/willmcpherson2/notcord/wiki/API)

**Comment by Stokeometry** [comment]
Just run some test & I've definatly made a mistake in the SQLlite syntax for deleting user from all channels in group

**Comment by minimuscle** [comment]
once its finished let me know, and I'll implement the deletion of the group. While you are at it, maybe have a deletion of channels too.

**Comment by Stokeometry** [comment]
Ok, my test are no longer throwing up errors on the sql, so it should work now
