### ISSUE TITLE
Users cannot decline invites.

### ISSUE THREAD

**Issue by minimuscle** [willmcpherson2/notcord#24]
Users should be able to decline invites, yet they currently cannot do this. I'd set this up just so it removes the invite, and so they can be invited again if need be.

**Comment by Stokeometry** [comment]
Ok i've rewiten the accept invite route into a process_group_invite route.

the route name accepts a bool as part of the input that determines if the invite is accepted or rejected. Will push on the backend, once if updated the API

**Comment by Stokeometry** [comment]
Should work now & the tests & API have been updated to reflect the changes.

**Comment by minimuscle** [comment]
User can now decline. Alerts have been updated.
