### ISSUE TITLE
Front-end doesn't know if user is admin. Add is_admin route

### ISSUE THREAD

**Issue by minimuscle** [willmcpherson2/notcord#26]
As the title says, the front end can't see if a user is an admin or not. Considering we can only have 1 admin at a time, I'll remove them from being able to remove themselves from channels and groups. If they leave the group, it will also delete the group if they are admin (with confirmation of course) See issue #25

**Comment by Stokeometry** [comment]
added an is_group_admin route, that takes a group_name and returns ok if current user is admin of group, err:permission_denied if not

**Comment by minimuscle** [comment]
Can I request it takes "username" as well, and returns if the user of that group is an admin. That will allow me to hide the ability for users to disable permissions for channel.

It works as is, but the visual looks as if you can remove permissions from an admin. You cannot, but the user wouldn't know this.

**Comment by Stokeometry** [comment]
ok, it now takes a username & group name, then if the logged in user is a member of the group it will return an ok::Conditional(bool), where bool is true if there username is admin, false if not.
