### ISSUE TITLE
Deleting channel from group deletes all channels with same name

### ISSUE THREAD

**Issue by minimuscle** [willmcpherson2/notcord#28]
When you delete a channel from a group, it will delete than channel from every group that has the same name. Channels need to have a unique ID thats not their name.

**Comment by willmcpherson2** [comment]
Bug is here
https://github.com/willmcpherson2/notcord/blob/a75055b21c7b9e36663d37c4df6571379fd01780/src/routes.rs#L587

**Comment by Stokeometry** [comment]
changed problematic line 

`"DELETE FROM channels INNER JOIN group_channels ON channels.ROWID = group_channels.channel_id WHERE name=?1 AND group_id=?2"`

testing is still ongoing

**Comment by Stokeometry** [comment]
Tests up SQLlite doesnt like DELETE from INNERJOINs so I had to use a subquery instead.

`"DELETE FROM channels WHERE ROWID IN (SELECT channel_id FROM channels INNER JOIN group_channels ON channels.ROWID = group_channels.channel_id WHERE name=?1 AND group_id=?2)"`

Ran some basic tests & it seems to work.
